#!/usr/bin/env bash
set -euo pipefail

# This script was generated by claude then revised and modified by me

TODO_DIR="$HOME/Documents/0.Personal/0.Journal/daily"
mkdir -p "$TODO_DIR"

today="$TODO_DIR/$(date +%F).md"
yesterday="$TODO_DIR/$(date -d 'yesterday' +%F).md"

if [[ -f "$today" ]]; then
  echo "Already exists: $today"
  exit 0
fi

extract_section() {
  local file="$1" heading="$2"
  awk -v h="$heading" '
        $0 ~ "^#"h":?[[:space:]]*$" { grab=1; next }
        /^#/ && grab { exit }
        grab { print }
    ' "$file"
}

weekly=""
if [[ -f "$yesterday" ]]; then
  weekly="$(extract_section "$yesterday" "Weekly")"
  weekly="$(echo "$weekly" | sed -e '/./,$!d' -e ':a' -e '/^\n*$/{$d;N;ba' -e '}')"
fi

{
  echo "#TODO"
  echo
  echo "- "
  echo
  echo "#Weekly Notes"
  echo
  if [[ -n "$weekly" ]]; then
    echo "$weekly"
  else
    echo "- "
  fi
  echo
  echo "#Journal"
  echo
  echo "- "
  echo
} >"$today"

echo "Created $today"
